### ISSUE TITLE
Зависимости в package.json

### ISSUE THREAD

**Issue by Magru** [Erlast/dz-lesson1-geekbrains-nodejs#1]
Привет, у тебя вроде в package.json не прописанны какие модули ты использовала, врода как их надо устанавливать с --save

**Comment by Erlast** [comment]
а все разобралась я вместо --save писала в консоли --safe
видимо поэтому и не дописалось в зависимости

>Воскресенье, 14 февраля 2016, 1:01 -08:00 от Maxim Fol <notifications@github.com>:
>
>Привет, у тебя вроде в package.json не прописанны какие модули ты использовала, врода как их надо устанавливать с --save
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Женя Абрамова
bunny9@bk.ru
